# Name of Workflow
name: github pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.92.1'

    - name: Clean public directory
      run: rm -rf public

    - name: Build
      run: |
          hugo mod get -u
          hugo --minify

    - name: Create CNAME and robots files
      run: |
          echo 'User-agent: *' > public/robots.txt
          echo '' >> public/robots.txt
          echo 'Disallow: /static/' >> public/robots.txt
          echo 'Disallow: /data/' >> public/robots.txt
          echo 'Disallow: /content/' >> public/robots.txt

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
